flasktest/games/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, SelectField
from wtforms.validators import DataRequired, Length, ValidationError

from flasktest.games.utils import Wordle


class WordleWordCheck:
    def __init__(self, allowed_words, message=None):
        self.allowed_words = allowed_words

        if not message:
            message = "Word not accepted!"
        self.message = message

    def __call__(self, form, field):
        if not field.data.lower() in self.allowed_words:
            raise ValidationError(self.message)


class CountryForm(FlaskForm):
    """
    Select form for countries page.
    """
    select = SelectField(label="Larger or Smaller?",
                         choices=[("Larger", "Larger"), ("Smaller", "Smaller")])
    submit = SubmitField(label="Go!")


class WordleForm(FlaskForm):
    """
    Word guess form for wordle page.
    """
    guess = StringField(render_kw={"placeholder": "Guess a word", "autofocus": True},
                        validators=[DataRequired(message="Please make a guess!"),
                                    Length(min=5, max=5,
                                           message="5 letters only!"),
                                    WordleWordCheck(
                                        message="Word not accepted!",
                                        allowed_words=Wordle.word_list)])
    submit = SubmitField(label="Guess!")


class NumbersForm(FlaskForm):
    """
    Submit form for numbers page.
    """
    submit = SubmitField(label="Stop")

flasktest/games/routes.py
import time

from flask import render_template, request, session
from flask_login import login_required

from flasktest import db
from flasktest.models import CountriesData, WordleData, NumbersData, start_new_wordle,\
    play_wordle_game, get_last_wordle_guess
from flasktest.games.forms import CountryForm, WordleForm, NumbersForm
from flasktest.games.utils import get_country_name, get_country_size, get_country_path,\
    evaluate_countries_game, create_numbers_divs

from flask import Blueprint

games = Blueprint("games", __name__)


@games.route("/games/countries", methods=["GET", "POST"])
@login_required
def countries():
    country_form = CountryForm()
    countries_data = CountriesData.query.filter_by(user_id=session["id"]).first()

    if request.method == "GET":
        return render_template("/games/countries.html",
                               country_form=country_form,
                               name1=get_country_name(countries_data.country_old),
                               size1=get_country_size(countries_data.country_old),
                               path1=get_country_path(countries_data.country_old),
                               name2=get_country_name(countries_data.country_new),
                               size2=get_country_size(countries_data.country_new),
                               path2=get_country_path(countries_data.country_new),
                               country_streak=countries_data.country_streak,
                               page="countries",
                               country_record=countries_data.country_record)

    if country_form.validate_on_submit():
        guess = country_form.select.data
        countries_data = evaluate_countries_game(guess=guess, user_id=session["id"])

        return render_template("/games/countries.html",
                               country_form=country_form,
                               name1=get_country_name(countries_data.country_old),
                               size1=get_country_size(countries_data.country_old),
                               path1=get_country_path(countries_data.country_old),
                               name2=get_country_name(countries_data.country_new),
                               size2=get_country_size(countries_data.country_new),
                               path2=get_country_path(countries_data.country_new),
                               country_streak=countries_data.country_streak,
                               country_record=countries_data.country_record,
                               page="countries",
                               scrollToAnchor="country-location")


@games.route("/games/wordle", methods=["POST", "GET"])
@login_required
def wordle():
    return render_template("games/wordle.html", page="wordle")


@games.route("/games/play-wordle", methods=["POST", "GET"])
@login_required
def play_wordle():
    wordle_form = WordleForm()
    # Get the users last played game
    descending = WordleData.query.order_by(WordleData.id.desc())
    wordle_data = descending.filter_by(user_id=session["id"]).first()

    # No games played yet
    if not wordle_data:
        # Start new game
        wordle_divs = start_new_wordle(session["id"])
        return render_template("games/play_wordle.html",
                               wordle_form=wordle_form,
                               wordle_divs=wordle_divs,
                               page="play_wordle")

    # Last game finished
    if wordle_data.wordle_game_state in ("win", "loss"):
        # Start new game
        wordle_divs = start_new_wordle(session["id"])
        return render_template("games/play_wordle.html",
                               wordle_form=wordle_form,
                               wordle_divs=wordle_divs,
                               page="play_wordle")

    # There is an active game
    if wordle_form.validate_on_submit():
        # Call play game function
        game_state, wordle_divs = play_wordle_game(wordle_guess=wordle_form.guess.data,
                                                   user_id=session["id"])

        return render_template("games/play_wordle.html",
                               wordle_form=wordle_form,
                               wordle_divs=wordle_divs,
                               game_state=game_state,
                               page="play_wordle")

    # GET request
    # Need last guessed word to recreate game state
    last_wordle_guess = get_last_wordle_guess(wordle_data=wordle_data)
    game_state, wordle_divs = play_wordle_game(wordle_guess=last_wordle_guess,
                                               user_id=session["id"])

    return render_template("games/play_wordle.html",
                           wordle_form=wordle_form,
                           wordle_divs=wordle_divs,
                           game_state=game_state,
                           page="play_wordle")


@games.route("/games/numbers", methods=["POST", "GET"])
@login_required
def numbers():
    numbers_form = NumbersForm()
    numbers_divs = create_numbers_divs()

    # Get users last unfinished game
    numbers_data = db.session.query(NumbersData)\
        .order_by(NumbersData.id.desc())\
        .filter(NumbersData.user_id == session["id"])\
        .first()
    # Get best times global
    numbers_highscores_all = db.session.query(NumbersData)\
        .order_by(NumbersData.numbers_time)\
        .filter(NumbersData.numbers_time > 0).limit(8)\
        .all()
    # Get best times personal
    numbers_highscores_self = db.session.query(NumbersData)\
        .order_by(NumbersData.numbers_time)\
        .filter(NumbersData.numbers_time > 0, NumbersData.user_id == session["id"]).limit(8)\
        .all()

    # Never played before
    if numbers_data is None:
        new_numbers = NumbersData(
            user_id=session["id"],
            numbers_start=time.time(),
        )
        db.session.add(new_numbers)
        db.session.commit()
        return render_template("/games/numbers.html",
                               numbers_form=numbers_form,
                               numbers_divs=numbers_divs,
                               numbers_highscores_self=numbers_highscores_self,
                               numbers_highscores_all=numbers_highscores_all,
                               page="numbers",
                               )

    # Played before and last game is over
    if numbers_data.numbers_time != -1:
        new_numbers = NumbersData(
            user_id=session["id"],
            numbers_start=time.time(),
        )
        db.session.add(new_numbers)
        db.session.commit()
        return render_template("/games/numbers.html",
                               numbers_form=numbers_form,
                               numbers_divs=numbers_divs,
                               numbers_highscores_self=numbers_highscores_self,
                               numbers_highscores_all=numbers_highscores_all,
                               page="numbers",
                               )

    # Game is going on pressed stop
    if numbers_form.validate_on_submit():
        numbers_data.numbers_stop = time.time()
        numbers_data.numbers_time = round((numbers_data.numbers_stop - numbers_data.numbers_start),
                                          4)
        db.session.commit()
        return render_template("/games/numbers.html",
                               numbers_form=numbers_form,
                               numbers_divs=numbers_divs,
                               numbers_highscores_self=numbers_highscores_self,
                               numbers_highscores_all=numbers_highscores_all,
                               page="numbers",
                               )

    # Game is going on and restarted
    if numbers_data.numbers_stop == -1:
        db.session.delete(numbers_data)
        db.session.commit()
        new_numbers = NumbersData(
            user_id=session["id"],
            numbers_start=time.time(),
        )
        db.session.add(new_numbers)
        db.session.commit()
        return render_template("/games/numbers.html",
                               numbers_form=numbers_form,
                               numbers_divs=numbers_divs,
                               numbers_highscores_self=numbers_highscores_self,
                               numbers_highscores_all=numbers_highscores_all,
                               page="numbers",
                               )

flasktest/templates/games/countries.html
{% extends "base.html" %}

{% block title %}
Countries
{% endblock %}

{% block scripts %}
    {% if scrollToAnchor %}
        <script>
        document.addEventListener("DOMContentLoaded", function() {
            document.location.hash = '#{{ scrollToAnchor }}';
        });

        </script>
        {% endif %}
{% endblock %}

{% block content %}
<section id="title-section">
    <div class="container title-container">
        <div class="row">
            <div class="header header-text col-lg-6 md-12">

                <h1 class="start">Show</h1>
                <br>
                <h4>off your knowledge of the European continent. Guess which country has the largest landmass and see
                    if you can beat your friends high-score.</h4>
            </div>

            <div class="header header-image col-lg-6 md-12">
                <img class="europe-logo" src="../static/images/games/countries/countries_logo.png">
            </div>
        </div>
    </div>

    <div id="country-location" class="container card-container">
        <div class="row">
            <div class="col-md-6 card-width">
                <div class="card text-white" style="border-radius: 1rem;">
                    <div class="card-body p-5 text-center">
                        <div class="mb-md-3 mt-md-4">

                            <h2 class="fw-bold mb-5 text-uppercase">
                                {{ name1 }}
                            </h2>

                            <div>
                                <img class="country-image mb-2" src="{{ path1 }}">
                            </div>

                            <p class="text-white-50 mb-0">
                                Size:
                            </p>

                            <p class="country-size mb-2 pb-3">
                                {{ size1 }} km<sup>2</sup>
                            </p>

                            <p class="text-white-50 mb-0 pb-0">
                                Current streak:
                            </p>

                            <p class="country-streak mb-2 pb-0">
                                {{ country_streak }}
                            </p>

                            <p class="text-white-50 mb-0 pb-0">
                                Record:
                            </p>

                            <p class="country-streak mb-2">
                                {{ country_record }}
                            </p>

                        </div>
                    </div>
                </div>
            </div>

            <div class="col-md-6 card-width">
                <div class="card text-white" style="border-radius: 1rem;">
                    <div class="card-body p-5 text-center">
                        <div class="mb-md-3 mt-md-4">

                            <h2 class="fw-bold mb-5 text-uppercase">{{ name2 }}</h2>

                            <div class="mb-4">
                                <img class="country-image"
                                     src="{{ path2 }}">
                            </div>

                            <form method="POST" action="" novalidate>
                                {{ country_form.hidden_tag() }}

                                <div class="form-group">
                                    <p class="text-white-50">{{ country_form.select.label }}</p>
                                    {{ country_form.select(class="form-control form-control-lg") }}

                                    <div class="form-group mb-3 mt-5">
                                        {{ country_form.submit(class="btn btn-outline-light btn-lg px-5") }}
                                    </div>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

<div class="transform-middle-light">
</div>

<section id="first-section">
</section>

<div class="transform-light-dark">
</div>
<section id="second-section">

</section>
{% endblock %}

flasktest/templates/games/numbers.html
{% extends "base.html" %}

{% block title %}
Numbers
{% endblock %}

{% block scripts %}
{% endblock %}

{% block content %}

<div class="transform-middle-light">
</div>

<section id="game-section">


    <div class="container numbers-container">

        <div class="numbers-scores">
            <ul>
                {% for time in numbers_highscores_self %}
                <li>{{ time.numbers_time }}</li>
                {% endfor %}
            </ul>
        </div>

        <div class="container game-container">
            <div class="game" id="allBoxes">
                {% for div in numbers_divs %}
                <div class="game-box">
                    <a id="{{ div[1] }}"><p>{{ div[0] }}</p></a>
                </div>
                {% endfor %}
            </div>
        </div>

        <div class="numbers-highscores">
            <ul>
                {% for time in numbers_highscores_all %}
                <li>{{ time.numbers_time }}</li>
                {% endfor %}
            </ul>
        </div>

    </div>


    <div class="container submit-container">

        <div class="start-container">
            <div class="game-start" id="test">
                <a href="#" id="boxStart">1</a>
            </div>
        </div>


        <form method="POST" action="" novalidate>
            {{ numbers_form.hidden_tag() }}

            <div class="play-button-container" id="boxStop">
                {{ numbers_form.submit(class="btn btn-outline-light btn-lg px-5") }}
            </div>

        </form>

        <div class="play-button-container">
            <a href="{{ url_for('games.numbers') }}" class="btn btn-outline-light btn-lg px-5">
                Reset!
            </a>
        </div>

    </div>
</section>

<div class="transform-light-dark">
</div>

<section id="second-section">
</section>

<script>
    $('#boxStart').on('click', function() {
        $('#test').css('display', 'none');
        $('#boxB').css('display', 'inline-block');
    });
    $('#boxB').on('click', function() {
        $('#boxB').css('display', 'none');
        $('#boxC').css('display', 'inline-block');
    });
    $('#boxC').on('click', function() {
        $('#boxC').css('display', 'none');
        $('#boxD').css('display', 'inline-block');
    });
    $('#boxD').on('click', function() {
        $('#boxD').css('display', 'none');
        $('#boxE').css('display', 'inline-block');
    });
    $('#boxE').on('click', function() {
        $('#boxE').css('display', 'none');
        $('#boxF').css('display', 'inline-block');
    });
    $('#boxF').on('click', function() {
        $('#boxF').css('display', 'none');
        $('#boxG').css('display', 'inline-block');
    });
    $('#boxG').on('click', function() {
        $('#boxG').css('display', 'none');
        $('#boxH').css('display', 'inline-block');
    });
    $('#boxH').on('click', function() {
        $('#boxH').css('display', 'none');
        $('#boxI').css('display', 'inline-block');
    });
    $('#boxI').on('click', function() {
        $('#boxI').css('display', 'none');
        $('#boxStop').css('display', 'inline-block');
    });



</script>

{% endblock %}

flasktest/templates/games/play_wordle.html
{% extends "base.html" %}

{% block title %}
Wordle
{% endblock %}

{% block scripts %}
{% endblock %}

{% block content %}

<div class="transform-middle-light">
</div>

<section id="game-section">
    <div class="container game-container">
        {% if game_state == "win" %}
            <h1>You win!</h1>
        {% elif game_state == "loss" %}
            <h1>You lose!</h1>
        {% endif %}

        <div class="game">
            {% for div in wordle_divs %}
            <div class="game-box" style="background-color:{{ div[1] }};">
                {{ div[0] }}
            </div>
            {% endfor %}
        </div>
    </div>

    <div class="container message-container">
        {% for message in get_flashed_messages() %}
            <div class="alert alert-warning" role="alert">
                {{ message }}
            </div>
        {% endfor %}
    </div>

    <div class="container submit-container">
        <form method="POST" action="" novalidate>
            {{ wordle_form.hidden_tag() }}

            <div class="form-group pt-0 pb-3">
                {% for error in wordle_form.errors["guess"] %}
                <p class="text-danger mb-1"><strong>{{ error }}</strong></p>
                {% endfor %}

                {% if game_win %}
                {% elif game_loss %}
                {% else %}

                {% if not get_flashed_messages() %}
                <p class="text-white-50 mb-1">Your 5-letter-word!</p>
                {% endif %}

                {{ wordle_form.guess(class="form-control form-control-lg") }}
                {% endif %}
            </div>

            {% if game_win %}
            <div class="container play-button-container">
                <a href="{{ url_for('games.play_wordle') }}" class="btn w-100 fw-bold pt-3 pb-3 text-uppercase text-white play-button">
                    Play again!
                </a>
            </div>
            {% elif game_loss %}
            <div class="container play-button-container">
                <a href="{{ url_for('games.play_wordle') }}" class="btn w-100 fw-bold pt-3 pb-3 text-uppercase text-white play-button">
                    Play again!
                </a>
            </div>
            {% else %}
            <div class="form-group py-3">
                {{ wordle_form.submit(class="btn btn-outline-light btn-lg px-5") }}
            </div>
            {% endif %}
        </form>
    </div>
</section>

<div class="transform-light-dark">
</div>

<section id="second-section">
</section>
{% endblock %}

flasktest/templates/games/wordle.html
{% extends "base.html" %}

{% block styles %}
<link rel="stylesheet" href="../static/css/wordle.css">
{% endblock %}

{% block title %}
Wordle
{% endblock %}

{% block scripts %}
{% endblock %}

{% block content %}
<section id="title-section">
    <div class="container title-container">
        <div class="row">
            <div class="header header-text col-lg-6 md-12">

                <h1 class="start">Guess</h1>
                <br>
                <h4>the right word in 6 tries! Each guess must be a valid 5-letter word and tiles will change color
                    corresponding to their placement.</h4>
            </div>

            <div class="header header-image col-lg-6 md-12">
                <img class="wordle-logo" src="../static/images/games/wordle/wordle_logo.png">
            </div>
        </div>
    </div>

    <div class="container play-button-container">
        <a href="{{ url_for('games.play_wordle') }}" class="btn w-100 fw-bold pt-3 pb-3 text-uppercase text-white play-button">
            Play
        </a>
    </div>

</section>

<div class="transform-middle-light">
</div>

<section id="first-section">
    <div class="container scores-container">
        <div class="row">
            <div class="col-lg-4 col-md-6 col-sm-12">
                <div class="card text-white" style="border-radius: 1rem;">
                    <div class="card-body p-5 text-center">
                        <div class="score-card mb-md-3 mt-md-4 scores-card-height">

                            <h2 class="fw-bold mb-5 text-uppercase">
                                Best average
                            </h2>

                            <p class="text-white-50 mb-0">
                                <!--{{ average1 }}-->Player1 2.4
                            </p>

                            <p class="text-white-50 mb-0">
                                <!--{{ average2 }}-->Player2 2.7
                            </p>

                            <p class="text-white-50 mb-0">
                                <!--{{ average3 }}-->Player3 3.0
                            </p>

                        </div>
                    </div>
                </div>
            </div>

            <div class="col-lg-4 col-md-6 col-sm-12 scores-card-width">
                <div class="card text-white" style="border-radius: 1rem;">
                    <div class="card-body p-5 text-center">
                        <div class="mb-md-3 mt-md-4 scores-card-height">

                            <h2 class="fw-bold mb-5 text-uppercase">
                                Most wins
                            </h2>

                            <p class="text-white-50 mb-0">
                                <!--{{ most1 }}-->Player1 12
                            </p>

                            <p class="text-white-50 mb-0">
                                <!--{{ most2 }}-->Player2 11
                            </p>

                            <p class="text-white-50 mb-0">
                                <!--{{ most3 }}-->Player3 9
                            </p>

                        </div>
                    </div>
                </div>
            </div>


            <div class="col-lg-4 col-md-6 col-sm-12 scores-card-width">
                <div class="card text-white" style="border-radius: 1rem;">
                    <div class="card-body p-5 text-center">
                        <div class="mb-md-3 mt-md-4 scores-card-height">

                            <h2 class="fw-bold mb-5 text-uppercase">
                                Least fails
                            </h2>

                            <p class="text-white-50 mb-0">
                                <!--{{ least1 }}-->Player1 1
                            </p>

                            <p class="text-white-50 mb-0">
                                <!--{{ least2 }}-->Player2 3
                            </p>

                            <p class="text-white-50 mb-0">
                                <!--{{ least3 }}-->Player4 4
                            </p>

                        </div>
                    </div>
                </div>
            </div>


        </div>
    </div>
</section>

<div class="transform-light-dark">
</div>
<section id="second-section">

</section>
{% endblock %}