flasktest/apis/routes.py
import time
import os

from flask import render_template, request, flash
from flask_login import login_required

from flasktest.models import APIData
from flasktest.apis.forms import SearchPUBGForm
from flasktest.apis.utils import get_player_id, get_seasons, get_all_season_stats, \
    create_dataframe, create_kills_bar, create_damage_bar, create_distance_bar,\
    load_old_pubg_data, get_pubg_cooldown_message, update_pubg_api_data

from flask import Blueprint

apis = Blueprint("apis", __name__)


@apis.route("/api/pubg", methods=["POST", "GET"])
@login_required
def pubg():
    pubg_form = SearchPUBGForm()
    kills_img = "../static/images/api/pubg/example_kills.png"
    damage_img = "../static/images/api/pubg/example_damage.png"
    distance_img = "../static/images/api/pubg/example_distance.png"
    df_path = "flasktest/static/data/api/pubg/df_"
    pubg_data = APIData.query.filter_by(api_name="pubg").first()

    if request.method == "GET":
        return render_template("/api/pubg.html", pubg_form=pubg_form, kills_img=kills_img,
                               damage_img=damage_img, distance_img=distance_img, page="pubg")

    if pubg_form.validate_on_submit():
        name = pubg_form.name.data
        game_mode = pubg_form.game_mode.data + pubg_form.perspective.data
        save_mode = game_mode.replace("-", "_")

        # Check for existing data before contacting API
        if os.path.exists(f"{df_path}{name}_{save_mode}.csv"):
            kills_img, damage_img, distance_img = \
                load_old_pubg_data(df_path, name, game_mode, save_mode)

            return render_template("/api/pubg.html", pubg_form=pubg_form, kills_img=kills_img,
                                   damage_img=damage_img, distance_img=distance_img,
                                   scrollToAnchor="pubg-section", page="pubg")

        # No data found - contact API
        # Check API availability
        if (pubg_data.last_used + 60) > time.time():
            # API used in last 60 seconds
            flash_message = get_pubg_cooldown_message()
            flash(flash_message)
            return render_template("/api/pubg.html", pubg_form=pubg_form, kills_img=kills_img,
                                   damage_img=damage_img, distance_img=distance_img,
                                   scrollToAnchor="pubg-section", page="pubg")

        id_code, id_response = get_player_id(name)
        if not id_code == 200:
            # Unsuccessful request - see pubg_imp.py for more info
            if id_code == 429:
                # Request limit reached
                update_pubg_api_data()

            flash_message = id_response
            flash(flash_message)
            return render_template("/api/pubg.html", pubg_form=pubg_form, kills_img=kills_img,
                                   damage_img=damage_img, distance_img=distance_img,
                                   scrollToAnchor="pubg-section", page="pubg")

        player_id = id_response
        # Player ID retrieved successfully
        seasons_code, seasons_response = get_seasons()
        if not seasons_code == 200:
            # Unsuccessful request - see pubg_imp.py for more info
            flash_message = seasons_response
            if seasons_code == 429:
                # Request limit reached
                update_pubg_api_data()

            flash(flash_message)
            return render_template("/api/pubg.html", pubg_form=pubg_form, kills_img=kills_img,
                                   damage_img=damage_img, distance_img=distance_img,
                                   scrollToAnchor="pubg-section", page="pubg")

        valid_seasons = seasons_response
        # Valid seasons retrieved successfully
        stats_code, stats_response = get_all_season_stats(player_id, valid_seasons, game_mode)
        if not stats_code == 200:
            # Unsuccessful request - see pubg_imp.py for more info
            flash_message = stats_response
            if stats_code == 429:
                # Request limit reached
                update_pubg_api_data()

            flash(flash_message)
            return render_template("/api/pubg.html", pubg_form=pubg_form, kills_img=kills_img,
                                   damage_img=damage_img, distance_img=distance_img,
                                   scrollToAnchor="pubg-section", page="pubg")

        player_stats = stats_response
        # Player stats retrieved successfully
        if len(player_stats[0]) < 2:
            # Check if player was active in at least 2 seasons, else draw no graph
            flash("Player has insufficient stats to generate graph")
            return render_template("/api/pubg.html", pubg_form=pubg_form, kills_img=kills_img,
                                   damage_img=damage_img, distance_img=distance_img,
                                   scrollToAnchor="pubg-section", page="pubg")

        # Success
        new_df = create_dataframe(player_stats, name, save_mode)
        kills_img = create_kills_bar(new_df, name, game_mode)
        damage_img = create_damage_bar(new_df, name, game_mode)
        distance_img = create_distance_bar(new_df, name, game_mode)
        # Update api db with timestamp
        update_pubg_api_data()
        return render_template("/api/pubg.html", pubg_form=pubg_form, kills_img=kills_img,
                               damage_img=damage_img, distance_img=distance_img,
                               scrollToAnchor="pubg-section", page="pubg")

    # Form not validated
    return render_template("/api/pubg.html", pubg_form=pubg_form, kills_img=kills_img,
                           damage_img=damage_img, distance_img=distance_img,
                           scrollToAnchor="pubg-section", page="pubg")

flasktest/games/routes.py
import time

from flask import render_template, request, session
from flask_login import login_required

from flasktest import db
from flasktest.models import CountriesData, WordleData, NumbersData, start_new_wordle,\
    play_wordle_game, get_last_wordle_guess
from flasktest.games.forms import CountryForm, WordleForm, NumbersForm
from flasktest.games.utils import get_country_name, get_country_size, get_country_path,\
    evaluate_countries_game, create_numbers_divs

from flask import Blueprint

games = Blueprint("games", __name__)


@games.route("/games/countries", methods=["GET", "POST"])
@login_required
def countries():
    country_form = CountryForm()
    countries_data = CountriesData.query.filter_by(user_id=session["id"]).first()

    if request.method == "GET":
        return render_template("/games/countries.html",
                               country_form=country_form,
                               name1=get_country_name(countries_data.country_old),
                               size1=get_country_size(countries_data.country_old),
                               path1=get_country_path(countries_data.country_old),
                               name2=get_country_name(countries_data.country_new),
                               size2=get_country_size(countries_data.country_new),
                               path2=get_country_path(countries_data.country_new),
                               country_streak=countries_data.country_streak,
                               page="countries",
                               country_record=countries_data.country_record)

    if country_form.validate_on_submit():
        guess = country_form.select.data
        countries_data = evaluate_countries_game(guess=guess, user_id=session["id"])

        return render_template("/games/countries.html",
                               country_form=country_form,
                               name1=get_country_name(countries_data.country_old),
                               size1=get_country_size(countries_data.country_old),
                               path1=get_country_path(countries_data.country_old),
                               name2=get_country_name(countries_data.country_new),
                               size2=get_country_size(countries_data.country_new),
                               path2=get_country_path(countries_data.country_new),
                               country_streak=countries_data.country_streak,
                               country_record=countries_data.country_record,
                               page="countries",
                               scrollToAnchor="country-location")


@games.route("/games/wordle", methods=["POST", "GET"])
@login_required
def wordle():
    return render_template("games/wordle.html", page="wordle")


@games.route("/games/play-wordle", methods=["POST", "GET"])
@login_required
def play_wordle():
    wordle_form = WordleForm()
    # Get the users last played game
    descending = WordleData.query.order_by(WordleData.id.desc())
    wordle_data = descending.filter_by(user_id=session["id"]).first()

    # No games played yet
    if not wordle_data:
        # Start new game
        wordle_divs = start_new_wordle(session["id"])
        return render_template("games/play_wordle.html",
                               wordle_form=wordle_form,
                               wordle_divs=wordle_divs,
                               page="play_wordle")

    # Last game finished
    if wordle_data.wordle_game_state in ("win", "loss"):
        # Start new game
        wordle_divs = start_new_wordle(session["id"])
        return render_template("games/play_wordle.html",
                               wordle_form=wordle_form,
                               wordle_divs=wordle_divs,
                               page="play_wordle")

    # There is an active game
    if wordle_form.validate_on_submit():
        # Call play game function
        game_state, wordle_divs = play_wordle_game(wordle_guess=wordle_form.guess.data,
                                                   user_id=session["id"])

        return render_template("games/play_wordle.html",
                               wordle_form=wordle_form,
                               wordle_divs=wordle_divs,
                               game_state=game_state,
                               page="play_wordle")

    # GET request
    # Need last guessed word to recreate game state
    last_wordle_guess = get_last_wordle_guess(wordle_data=wordle_data)
    game_state, wordle_divs = play_wordle_game(wordle_guess=last_wordle_guess,
                                               user_id=session["id"])

    return render_template("games/play_wordle.html",
                           wordle_form=wordle_form,
                           wordle_divs=wordle_divs,
                           game_state=game_state,
                           page="play_wordle")


@games.route("/games/numbers", methods=["POST", "GET"])
@login_required
def numbers():
    numbers_form = NumbersForm()
    numbers_divs = create_numbers_divs()

    # Get users last unfinished game
    numbers_data = db.session.query(NumbersData)\
        .order_by(NumbersData.id.desc())\
        .filter(NumbersData.user_id == session["id"])\
        .first()
    # Get best times global
    numbers_highscores_all = db.session.query(NumbersData)\
        .order_by(NumbersData.numbers_time)\
        .filter(NumbersData.numbers_time > 0).limit(8)\
        .all()
    # Get best times personal
    numbers_highscores_self = db.session.query(NumbersData)\
        .order_by(NumbersData.numbers_time)\
        .filter(NumbersData.numbers_time > 0, NumbersData.user_id == session["id"]).limit(8)\
        .all()

    # Never played before
    if numbers_data is None:
        new_numbers = NumbersData(
            user_id=session["id"],
            numbers_start=time.time(),
        )
        db.session.add(new_numbers)
        db.session.commit()
        return render_template("/games/numbers.html",
                               numbers_form=numbers_form,
                               numbers_divs=numbers_divs,
                               numbers_highscores_self=numbers_highscores_self,
                               numbers_highscores_all=numbers_highscores_all,
                               page="numbers",
                               )

    # Played before and last game is over
    if numbers_data.numbers_time != -1:
        new_numbers = NumbersData(
            user_id=session["id"],
            numbers_start=time.time(),
        )
        db.session.add(new_numbers)
        db.session.commit()
        return render_template("/games/numbers.html",
                               numbers_form=numbers_form,
                               numbers_divs=numbers_divs,
                               numbers_highscores_self=numbers_highscores_self,
                               numbers_highscores_all=numbers_highscores_all,
                               page="numbers",
                               )

    # Game is going on pressed stop
    if numbers_form.validate_on_submit():
        numbers_data.numbers_stop = time.time()
        numbers_data.numbers_time = round((numbers_data.numbers_stop - numbers_data.numbers_start),
                                          4)
        db.session.commit()
        return render_template("/games/numbers.html",
                               numbers_form=numbers_form,
                               numbers_divs=numbers_divs,
                               numbers_highscores_self=numbers_highscores_self,
                               numbers_highscores_all=numbers_highscores_all,
                               page="numbers",
                               )

    # Game is going on and restarted
    if numbers_data.numbers_stop == -1:
        db.session.delete(numbers_data)
        db.session.commit()
        new_numbers = NumbersData(
            user_id=session["id"],
            numbers_start=time.time(),
        )
        db.session.add(new_numbers)
        db.session.commit()
        return render_template("/games/numbers.html",
                               numbers_form=numbers_form,
                               numbers_divs=numbers_divs,
                               numbers_highscores_self=numbers_highscores_self,
                               numbers_highscores_all=numbers_highscores_all,
                               page="numbers",
                               )

flasktest/main/routes.py
import random
import math
import smtplib
import time
import os

from flask import render_template
from flask_login import login_required

from flask import Blueprint

main = Blueprint("main", __name__)


@main.route("/home")
@login_required
def home():
    return render_template("home.html",
                           page="home")

flasktest/templates/base.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- Google Fonts -->
    <link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@300;400;500;600;700;800;900&display=swap" rel="stylesheet">
    <!-- Fav Icon -->
    <script src="https://kit.fontawesome.com/0a8b309a8e.js" crossorigin="anonymous"></script>
    <!-- Font awesome -->
    <script src="https://kit.fontawesome.com/0a8b309a8e.js" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.3.0/css/all.min.css"
          integrity="sha512-SzlrxWUlpfuzQ+pcUCosxcglQRNAq/DZjVsC0lE40xsADsfeQoEypE+enwcOiGjk/bSuGGKHEyjSoQ1zVisanQ=="
          crossorigin="anonymous" referrerpolicy="no-referrer"/>
    <!-- Bootstrap -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
    <!-- jQuery scripts -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
    <!-- Style sheets -->
    <link rel="stylesheet" href="../static/css/base.css">
    {% if page == "home" %}
    <link rel="stylesheet" href="../static/css/home.css">
    {% elif page == "pubg" %}
    <link rel="stylesheet" href="../static/css/pubg.css">
    {% elif page == "countries" %}
    <link rel="stylesheet" href="../static/css/countries.css">
    {% elif page == "numbers" %}
    <link rel="stylesheet" href="../static/css/numbers.css">
    {% elif page == "wordle" %}
    <link rel="stylesheet" href="../static/css/wordle.css">
    {% elif page == "play_wordle" %}
    <link rel="stylesheet" href="../static/css/play_wordle.css">
    {% endif %}

    <title>
        {% block title %}
        {% endblock %}
    </title>

    {% block scripts %}
    {% endblock %}

</head>
<body>


<section id="navbar-section">
    <nav class="navbar navbar-expand-lg navbar-expand-md">

        <a class="navbar-brand" href="{{ url_for('main.home') }}">Tomas W</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav"
                aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav ms-auto">

                <li class="nav-item">
                    <a class="nav-link" href="#">Skills</a>
                </li>

                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink1" data-toggle="dropdown"
                       aria-haspopup="true" aria-expanded="false">
                        Data
                    </a>

                    <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink1">
                        <a class="dropdown-item" href="{{ url_for('apis.pubg') }}">PUBG</a>
                        <a class="dropdown-item" href="#">Another action</a>
                        <a class="dropdown-item" href="#">Something else here</a>
                    </div>
                </li>

                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink2" data-toggle="dropdown"
                       aria-haspopup="true" aria-expanded="false">
                        Games
                    </a>
                    <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink2">
                        <a class="dropdown-item" href="{{ url_for('games.countries') }}">Countries</a>
                        <a class="dropdown-item" href="{{ url_for('games.wordle') }}">Wordle</a>
                        <a class="dropdown-item" href="{{ url_for('games.numbers') }}">Numbers</a>
                    </div>
                </li>

                <li class="nav-item">
                    <a class="nav-link" href="#">Coming</a>
                </li>

                <li class="nav-item">
                    <a class="nav-link" href="{{ url_for('users.logout') }}">Log out</a>
                </li>
            </ul>
        </div>
    </nav>

</section>

{% block content %}

{% endblock %}

<!-- Bootstrap scripts -->
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.14.3/dist/umd/popper.min.js"
        integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49"
        crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.1.3/dist/js/bootstrap.min.js"
        integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy"
        crossorigin="anonymous"></script>

</body>
</html>

flasktest/templates/landing_base.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- Google Fonts Josefin Sans -->
    <link href="https://fonts.googleapis.com/css2?family=Josefin+Sans:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;1,100;1,200;1,300;1,400;1,500;1,600;1,700&display=swap"
          rel="stylesheet">
    <!-- Fav Icon -->
    <script src="https://kit.fontawesome.com/0a8b309a8e.js" crossorigin="anonymous"></script>
    <!-- Bootstrap -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
    <!-- jQuery scripts -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
    <!-- Style sheets -->
    <link rel="stylesheet" href="../static/css/landing_base.css">

    <title>
        {% block landing_title %}
        {% endblock %}
    </title>

</head>
<body>

{% block landing_content %}
{% endblock %}

<!-- Bootstrap scripts -->
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.14.3/dist/umd/popper.min.js"
        integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49"
        crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.1.3/dist/js/bootstrap.min.js"
        integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy"
        crossorigin="anonymous"></script>

</body>
</html>