flasktest/users/routes.py
from flask import Blueprint

import random
import math
import smtplib
import time
import os

from flask import render_template, redirect, url_for, request, flash, session
from flask_login import login_user, login_required, logout_user

import flasktest.models
from flasktest import db, bcrypt
from flasktest.models import User, APIData, add_test_user, add_new_user
from flasktest.users.forms import RegisterForm, LoginForm, EmailForm, ResetForm

users = Blueprint("users", __name__)

GMAIL_EMAIL = os.environ["GMAIL_EMAIL"]
GMAIL_PASS = os.environ["GMAIL_PASS"]
GMAIL_SMTP = os.environ["GMAIL_SMTP"]
TEST_EMAIL = os.environ["TEST_EMAIL"]
TEST_EMAIL2 = os.environ["TEST_EMAIL2"]


@users.route("/")
def index():
    return redirect("login")


@users.route("/fresh")
def base():
    """Create two dummy accounts and API defaults after db reset"""
    hashed_password = bcrypt.generate_password_hash("test1234")
    add_test_user(email=TEST_EMAIL, username="test1", hashed_password=hashed_password)
    add_test_user(email=TEST_EMAIL2, username="test2", hashed_password=hashed_password)
    pubg_api = APIData(api_name="pubg", last_used=math.floor(time.time()), timer=60)
    db.session.add(pubg_api)
    db.session.commit()
    return redirect(url_for("users.login"))


@users.route("/login", methods=["GET", "POST"])
def login():
    login_form = LoginForm()
    register_form = RegisterForm()

    if request.method == "GET":
        return render_template("/landing/login.html",
                               login_form=login_form,
                               register_form=register_form)

    if login_form.validate_on_submit():
        user = User.query.filter_by(email=login_form.email.data).first()

        if not flasktest.models.do_passwords_match(user, login_form.password):
            flash("Password incorrect.")

        else:
            # Login successful
            login_user(user, remember=True)
            session["id"] = user.id
            return redirect(url_for("main.home"))

    # Unsuccessful attempts
    return render_template("/landing/login.html",
                           login_form=login_form,
                           register_form=register_form)


@users.route("/logout")
@login_required
def logout():
    logout_user()
    return redirect(url_for("users.login"))


@users.route("/register", methods=["GET", "POST"])
def register():
    register_form = RegisterForm()

    if request.method == "GET":
        return render_template("/landing/register.html",
                               register_form=register_form)

    if register_form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(register_form.password.data)
        add_new_user(
            email=register_form.email,
            username=register_form.username,
            hashed_password=hashed_password,
            )
        return redirect(url_for("users.login"))

    # Form not validated
    return render_template("/landing/register.html",
                           register_form=register_form)


@users.route("/request-reset", methods=["GET", "POST"])
def request_reset():
    email_form = EmailForm()

    if request.method == "GET":
        return render_template("/landing/request_reset.html",
                               email_form=email_form)

    # Request reset attempt
    if email_form.validate_on_submit():
        user = User.query.filter_by(email=email_form.email.data).first()

        reset_code = random.randint(100000, 999999)
        user.reset_key = reset_code
        db.session.commit()
        with smtplib.SMTP(GMAIL_SMTP) as connection:
            connection.starttls()
            connection.login(user=GMAIL_EMAIL, password=GMAIL_PASS)
            connection.sendmail(
                from_addr=GMAIL_EMAIL,
                to_addrs=user.email,
                msg=f"Subject:Reset Code\n\nYour reset code: {reset_code}"
            )
            flash("Code hes been send!")
            return redirect(url_for("users.enter_reset"))

    # Request reset form not validated
    return render_template("/landing/request_reset.html",
                           email_form=email_form)


@users.route("/enter-reset", methods=["GET", "POST"])
def enter_reset():
    reset_form = ResetForm()

    if request.method == "GET":
        return render_template("/landing/enter_reset.html",
                               reset_form=reset_form)

    # Reset attempt
    if reset_form.validate_on_submit():
        user = User.query.filter_by(email=reset_form.email.data).first()

        # User did not request a reset
        if user.reset_key == 000000 or None:
            flash("Unauthorised request!")
            return render_template("/landing/enter_reset.html",
                                   reset_form=reset_form)

        # Incorrect reset code
        if not user.reset_key == reset_form.reset_code.data:
            flash("Incorrect email or code!")
            return render_template("/landing/enter_reset.html",
                                   reset_form=reset_form)

        # Password reset successful
        hashed_password = bcrypt.generate_password_hash(reset_form.password.data)
        flasktest.models.change_password(user.id, hashed_password)
        return redirect("login")

    # Enter reset form not validated
    return render_template("/landing/enter_reset.html",
                           reset_form=reset_form)

flasktest/templates/landing/enter_reset.html
{% extends "landing_base.html" %}}


{% block landing_title %}
Login
{% endblock %}

{% block landing_content %}
<section class="login-height gradient-custom">
    <div class="container py-5 h-100">
        <div class="row d-flex justify-content-center align-items-center h-100">
            <div class="col-12 col-md-8 col-lg-6 col-xl-5">
                <div class="card bg-dark text-white" style="border-radius: 1rem;">

                    <div class="card-body p-5 text-center">

                        <div class="mb-md-5 mt-md-4 pb-3">
                            {% for message in get_flashed_messages() %}
                            <div class="alert alert-secondary" role="alert">
                                {{ message }}
                            </div>

                            {% endfor %}

                            <h2 class="fw-bold mb-2 text-uppercase">Reset</h2>
                            <p class="text-white-50 mb-5">Please confirm your email and reset code!</p>

                            <div class="form-outline form-white mb-4">

                                <form method="POST" action="" novalidate>
                                    {{ reset_form.hidden_tag() }}
                                    <div class="form-group py-3">
                                        {% for error in reset_form.errors["email"] %}
                                            <p class="text-danger mb-1"><strong>{{ error }}</strong></p>
                                        {% endfor %}

                                        <p class="text-white-50 mb-1">{{ reset_form.email.label }}</p>
                                        {{ reset_form.email(class="form-control form-control-lg") }}
                                    </div>

                                    <div class="form-group py-3">
                                        {% for error in reset_form.errors["reset_code"] %}
                                            <p class="text-danger mb-1"><strong>{{ error }}</strong></p>
                                        {% endfor %}

                                        <p class="text-white-50 mb-1">{{ reset_form.reset_code.label }}</p>
                                        {{ reset_form.reset_code(class="form-control form-control-lg") }}
                                    </div>

                                    <div class="form-group py-3">
                                        {% for error in reset_form.errors["password"] %}
                                            <p class="text-danger mb-1"><strong>{{ error }}</strong></p>
                                        {% endfor %}

                                        <p class="text-white-50 mb-1">{{ reset_form.password.label }}</p>
                                        {{ reset_form.password(class="form-control form-control-lg") }}
                                    </div>

                                    <div class="form-group py-3">
                                        {% for error in reset_form.errors["password2"] %}
                                            <p class="text-danger mb-1"><strong>{{ error }}</strong></p>
                                        {% endfor %}

                                        <p class="text-white-50 mb-1">{{ reset_form.password2.label }}</p>
                                        {{ reset_form.password2(class="form-control form-control-lg") }}
                                    </div>

                                    <div class="form-group pt-3">
                                        {{ reset_form.submit(class="btn btn-outline-light btn-lg px-5") }}
                                    </div>

                                </form>
                            </div>

                            <p class="small mb-5 pb-lg-2"><a class="text-white-50" href="{{ url_for('users.request_reset')  }}">Re-send code?</a></p>


                        </div>

                        <div>
                            <p class="mb-0">Don't have an account? <a href="{{ url_for('users.register')  }}"
                                                                      class="text-white-50 fw-bold">Sign Up</a>
                            </p>
                        </div>

                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
{% endblock %}

flasktest/templates/landing/login.html
{% extends "landing_base.html" %}}

{% block landing_title %}
Login
{% endblock %}

{% block landing_content %}
<section class="login-height gradient-custom">

    <div class="container card-container">
        <div class="row justify-content-center card-items">

            <div id="login-card" class="col-lg-4 col-md-8 col-sm-10 login-div">
                <div class="card bg-dark text-white" style="border-radius: 1rem;">
                    <div class="card-body p-5 text-center">
                        <div class="container">
                            {% for message in get_flashed_messages() %}
                            <div class="alert alert-secondary" role="alert">
                                {{ message }}
                            </div>
                            {% endfor %}

                            <h2 class="fw-bold mb-2 text-uppercase">Login</h2>
                            <p class="text-white-50 mb-5">Please enter your login details!</p>

                            <div class="form-outline form-white mb-4">
                                <form method="POST" action="" novalidate>
                                    {{ login_form.hidden_tag() }}

                                    <div class="form-group py-3">
                                        {% for error in login_form.errors["email"] %}
                                            <p class="text-danger mb-1"><strong>{{ error }}</strong></p>
                                        {% endfor %}

                                        <p class="text-white-50 mb-1">{{ login_form.email.label }}</p>
                                        {{ login_form.email(class="form-control form-control-lg") }}
                                    </div>

                                    <div class="form-group py-3">
                                        {% for error in login_form.errors["password"] %}
                                            <p class="text-danger mb-1"><strong>{{ error }}</strong></p>
                                        {% endfor %}

                                        <p class="text-white-50 mb-1">{{ login_form.password.label }}</p>
                                        {{ login_form.password(class="form-control form-control-lg") }}
                                    </div>

                                    <div class="form-group pt-3">
                                        {{ login_form.submit(class="btn btn-outline-light btn-lg px-5") }}
                                    </div>
                                </form>
                            </div>

                            <p class="small mb-5 pb-lg-2"><a class="text-white-50"
                                                             href="{{ url_for('users.request_reset')  }}">Forgot
                                password?</a></p>
                        </div>

                        <div>
                            <p class="mb-0">Don't have an account? <a href="{{ url_for('users.register') }}" id="getRegister"
                                                                      class="text-white-50 fw-bold">Sign Up</a>
                            </p>
                        </div>
                    </div>
                </div>
            </div>


        </div>
    </div>
</section>

{% endblock %}

flasktest/templates/landing/register.html
{% extends "landing_base.html" %}}


{% block landing_title %}
Register
{% endblock %}

{% block landing_content %}
<section class="login-height gradient-custom">
    <div class="container login-container py-5 h-100">
        <div class="row d-flex justify-content-center align-items-center h-100">
            <div class="col-12 col-md-8 col-lg-6 col-xl-5">



                <div class="card bg-dark text-white" style="border-radius: 1rem;">
                    <div class="card-body p-5 text-center">
                        <div class="mb-md-5 mt-md-4 pb-3">

                            {% for message in get_flashed_messages() %}
                            <div class="alert alert-secondary" role="alert">
                                {{ message }}
                            </div>
                            {% endfor %}

                            <h2 class="fw-bold mb-2 text-uppercase">Register</h2>
                            <p class="text-white-50 mb-5">Please enter your details!</p>


                            <div class="form-outline form-white mb-4">
                                <form method="POST" action="" novalidate>
                                    {{ register_form.hidden_tag() }}

                                    <div class="form-group py-3">
                                        {% for error in register_form.errors["email"] %}
                                            <p class="text-danger mb-1"><strong>{{ error }}</strong></p>
                                        {% endfor %}

                                        <p class="text-white-50 mb-1">{{ register_form.email.label }}</p>
                                        {{ register_form.email(class="form-control form-control-lg") }}
                                    </div>

                                    <div class="form-group py-3">
                                        {% for error in register_form.errors["username"] %}
                                            <p class="text-danger mb-1"><strong>{{ error }}</strong></p>
                                        {% endfor %}

                                        <p class="text-white-50 mb-1">{{ register_form.username.label }}</p>
                                        {{ register_form.username(class="form-control form-control-lg") }}
                                    </div>

                                    <div class="form-group py-3">
                                        {% for error in register_form.errors["password"] %}
                                            <p class="text-danger mb-1"><strong>{{ error }}</strong></p>
                                        {% endfor %}

                                        <p class="text-white-50 mb-1">{{ register_form.password.label }}</p>
                                        {{ register_form.password(class="form-control form-control-lg") }}
                                    </div>

                                    <div class="form-group py-3">
                                        {% for error in register_form.errors["password2"] %}
                                            <p class="text-danger mb-1"><strong>{{ error }}</strong></p>
                                        {% endfor %}

                                        <p class="text-white-50 mb-1">{{ register_form.password2.label }}</p>
                                        {{ register_form.password2(class="form-control form-control-lg") }}
                                    </div>

                                    <div class="form-group pt-3">
                                        {{ register_form.submit(class="btn btn-outline-light btn-lg px-5") }}
                                    </div>
                                </form>
                            </div>
                        </div>

                        <div>
                            <p class="mb-0">Already have an account? <a href="{{ url_for('users.login') }}"
                                                                        class="text-white-50 fw-bold">Log in</a>
                            </p>
                        </div>
                    </div>
                </div>



            </div>
        </div>
    </div>
</section>
{% endblock %}

flasktest/templates/landing/request_reset.html
{% extends "landing_base.html" %}}


{% block landing_title %}
Login
{% endblock %}

{% block landing_content %}

<section class="login-height gradient-custom">
    <div class="container py-5 h-100">
        <div class="row d-flex justify-content-center align-items-center h-100">
            <div class="col-12 col-md-8 col-lg-6 col-xl-5">
                <div class="card bg-dark text-white" style="border-radius: 1rem;">
                    <div class="card-body p-5 text-center">

                        <div class="mb-md-5 mt-md-4 pb-3">
                            {% for message in get_flashed_messages() %}
                            <div class="alert alert-secondary" role="alert">
                                {{ message }}
                            </div>
                            {% endfor %}

                            <h2 class="fw-bold mb-2 text-uppercase">Reset</h2>
                            <p class="text-white-50 mb-5">Please enter your email to receive a reset code!</p>

                            <div class="form-outline form-white mb-4">
                                <form method="POST" action="" novalidate>
                                    {{ email_form.hidden_tag() }}
                                    <div class="form-group py-3">
                                        <p class="text-white-50 mb-1">{{ email_form.email.label }}</p>
                                        {{ email_form.email(class="form-control form-control-lg") }}
                                    </div>

                                    <div class="form-group pt-3">
                                        {{ email_form.submit(class="btn btn-outline-light btn-lg px-5") }}
                                    </div>
                                </form>
                            </div>
                        </div>

                        <div>
                            <p class="mb-0">Don't have an account? <a href="{{ url_for('users.register')  }}"
                                                                      class="text-white-50 fw-bold">Sign Up</a>
                            </p>
                        </div>

                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
{% endblock %}

flasktest/templates/landing/reset_password.html
{% extends "landing_base.html" %}}

{% block landing_title %}
Login
{% endblock %}

{% block landing_content %}
<section class="login-height gradient-custom">
    <div class="container py-5 h-100">
        <div class="row d-flex justify-content-center align-items-center h-100">
            <div class="col-12 col-md-8 col-lg-6 col-xl-5">
                <div class="card bg-dark text-white" style="border-radius: 1rem;">
                    <div class="card-body p-5 text-center">

                        <div class="mb-md-5 mt-md-4 pb-3">
                            {% for message in get_flashed_messages() %}
                            <div class="alert alert-secondary" role="alert">
                                {{ message }}
                            </div>
                            {% endfor %}

                            <h2 class="fw-bold mb-2 text-uppercase">Reset</h2>
                            <p class="text-white-50 mb-5">Please enter your email and new password!</p>

                            <div class="form-outline form-white mb-4">
                                <form method="POST" action="" novalidate>
                                    {{ new_password_form.hidden_tag() }}
                                    <div class="form-group py-3">
                                        <p class="text-white-50 mb-1">{{ new_password_form.email.label }}</p>
                                        {{ new_password_form.email(class="form-control form-control-lg") }}
                                    </div>

                                    <div class="form-group py-3">
                                        <p class="text-white-50 mb-1">{{ new_password_form.password.label }}</p>
                                        {{ new_password_form.password(class="form-control form-control-lg") }}
                                    </div>

                                    <div class="form-group pt-3">
                                        {{ new_password_form.submit(class="btn btn-outline-light btn-lg px-5") }}
                                    </div>
                                </form>
                            </div>
                        </div>

                        <div>
                            <p class="mb-0">Don't have an account? <a href="{{ url_for('users.register')  }}"
                                                                      class="text-white-50 fw-bold">Sign Up</a>
                            </p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
{% endblock %}